# Generated by Django 2.1 on 2021-03-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
