# Generated by Django 2.1 on 2021-04-03 10:13

from django.db import migrations, models
import feed.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='path/to/video', validators=[feed.validators.file_size]),
        ),
    ]
