# Generated by Django 2.1 on 2021-04-03 10:58

from django.db import migrations, models
import feed.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='path/to/img', validators=[feed.validators.file_size]),
        ),
    ]
