# Generated by Django 3.1.7 on 2021-04-04 04:29

from django.db import migrations, models
import feed.validators


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='path/to/img', validators=[feed.validators.file_size]),
        ),
    ]
