# Generated by Django 3.1.7 on 2021-04-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, upload_to='path/to/img'),
        ),
    ]
